### ISSUE TITLE
closed bug / 503 issue?

### ISSUE THREAD

**Issue by darmbrust** [jobisoft/DAV-4-TbSync#100]
What is the actual fix for https://github.com/jobisoft/DAV-4-TbSync/issues/41 supposed to be?  I don't understand why it has been simply closed with a workaround required which decreases security.  And it doesn't work out of the box without tracing thru numerous bug reports to try to find out what is going on?  See also https://github.com/nextcloud/server/issues/10134 .  Is it tied to this?  https://bugzilla.mozilla.org/show_bug.cgi?id=1544596

Seems strange, because I'm only trying to set up a single account.

**Comment by jobisoft** [comment]
What Thunderbird version are you using? There was a general incompatibility between TB and nextcloud, which was even listed in the release notes of TB. Back than, the only fix was to set that cookie setting (which you refer to as decreased security?). That specific bug has been fixed somewhere on the road to TB 60.8 and the cookie setting is no longer needed. If you still get a 503, it is a different bug and pobably a server issue.

Bug 1544596 is a fix which I filed, which solves a different bug.

**Comment by lhorace** [comment]
Hello,

@jobisoft Just to verify, TB 60.8 or TB 68 ?

Regards

**Comment by jobisoft** [comment]
TB 60.8, the current official release of the 60.x branch.

68 will be released next month.

**Comment by darmbrust** [comment]
I was attempting to sync up with:
thunderbird 60.7.0, CalDav 0.15.0.2, TbSync 1.7 against NextCloud 16.0.3

I guess I assumed from other bugs I've seen that the setting defaults to true for some particular security reason... but that was just a guess.  Other bugs had workarounds that involved adding exceptions for just a single site, rather than the true/false toggle.

**Comment by darmbrust** [comment]
I do see I'm a tick behind on thunderbird now, according to my package manager (kubuntu).  I'll upgrade tomorrow, and test again with the setting toggled back.

**Comment by jobisoft** [comment]
I think it was fixed in 60.5.1. so updating is probably not needed, as the error must be somewhere else.

Try to create a fresh Thunderbird Profile (thunderbird-p) and test there.

**Comment by darmbrust** [comment]
Tested again with 60.8.0.  Same behavior.  Won't connect with network.cookie.same-site.enabled set to the default value - with either TbSync or the standard lightening CalDev mechanism.
Toggle it to false, and it syncs.

That said, while it syncs, and shows the right dates / times on the list view and on the calendar, trying to edit / view the details of any event that was created in nextcloud shows up completely wrong in the editor, with the times not set at all.  But guessing that is yet another lightening bug, since both TbSync and the native support have the same problem...and they appear right in some places....

The nextcloud bug report https://github.com/nextcloud/server/issues/10134 points to this mozilla bug https://bugzilla.mozilla.org/show_bug.cgi?id=1468912#c83 which they were calling the fix to this host of problems... but it seems that was incorrect, or at least, didn't solve all of them, since its still broken.

**Comment by jobisoft** [comment]
Sorry to hear that. I am 99% sure this is fixed as I saw the code changes and verified the fix.

It sounds like your lightning has not been updated and/or your profile is broken. Check your package manager (as your distribution has decoupled lightning from Thunderbird and ships lightning in its own package). 

I can test this again in 3 weeks, when I am back at my computer.

**Comment by darmbrust** [comment]
I'm not using the package maintainers version of lightning, I installed it directly into thunderbird as an extension from the mozilla update site.  

Thunderbird says all of my extensions are up to date, and reports I have 6.2.5 installed.  I am a bit confused, however, because some people on the other thread that can't reproduce the issue claim to be using 6.2.8.  But I don't see any 6.2.8 version..... https://addons.thunderbird.net/en-US/thunderbird/addon/lightning/versions/

Perhaps this is fixed in the latest... but the Lightning people just aren't properly releasing their updates?

**Comment by darmbrust** [comment]
Ok, guessing this is where the fix landed:
https://bugzilla.mozilla.org/buglist.cgi?resolution=FIXED&product=Calendar&target_milestone=6.2.5.1&list_id=14828679

6.2.5.1, while my calendar is still at 6.2.5.  According to this list:
https://developer.mozilla.org/en-US/docs/Mozilla/Calendar/Calendar_Versions
I'm like 5 versions behind on Lightning.... I know its not your issue, but what the heck is wrong with  the Lightning distribution that they aren't pushing their updates to the central update site?  

Sigh... reading more, it appears that they want you to uninstall the extension, cause its no longer necessary... as its supposed to be bundled.  That is the stupidest update path I've ever heard of.... something tells me they will bite a lot of people with this, when they didn't manage the extension properly for users that already had it installed.... and they aren't properly updating the update site, so if you installed it from there, the older version overrides the integrated version.

I'll retest after sorting this out, and close the bug.

**Comment by jobisoft** [comment]
Yes. Fixed in 6.2.5.1. Lightning update path indeed is strange, but your distribution has a dedicated lightning package. Install that.

The original Thunderbird has lightning bundled and you would not have run into this. Your distribution decided to decouple lightning from thunderbird.

I am an AddOn author. I have nothing at all to do with this.

John

**Comment by darmbrust** [comment]
Ok, this is still odd.

So, I removed the lightning from thunderbird... and then, since the Ubuntu maintainers stripped it, I had to install it from my package manager - finally got to version 6.2.8.

Now, I can connect to my calendar if I simply do it via the built in caldav service.

But if I use TBSync, its still broken - I simply get this:

```
Service Unavailable

URL:
https://myserver.net/nextcloud/remote.php/dav/calendars/darmbrust/stuff (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>

Response:
```

I think that I'm using the correct URL, though, the "discovery" option doesn't work for me, even though my nextcloud install claims it is set up properly for discovery.  Instead, I'm using the manual mode, and pasting in the link the nextcloud webapp provides to me.

I believe I have all of the current versions now:
Thunderbird: 60.8.0
Lightning 6.2.8
CalDAV provider 0.15.0.2
TBSync 1.7

Since it works for me using the native CalDav support, I'll just go back to that for now... but still a mystery why it isn't working with your addon.  Maybe my profile has something messed up from all of these attempts to fix it.... but since it has a working alternative, I'm not going to chase it anymore...

**Comment by jobisoft** [comment]
Glad it works for you now. 

Do not waste time on the 60.x branch.

When 68 is out next month, you could give it another try with TbSync 2.x which fixes lots of issues and is basically a rewrite. Also lightning 7.x fixes lots of issues.

John
