### ISSUE TITLE
JavaScript error/ interrupted sync on specific photo format (to nextcloud)

### ISSUE THREAD

**Issue by codeling** [jobisoft/DAV-4-TbSync#204]
## Your environment

TbSync version: 2.11
DAV-4-TbSync version: 1.9
Thunderbird version: 68.6.0

[x] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.

## Expected behavior
All my contacts from nextcloud should sync.

## Actual behavior
Only some (21 out of 248) do synchronize, and I get an error in the error console:
```
Javascript error! Please check event log for further details.
Account: nextcloud (DAV)
Resource: default

Component returned failure code: 0x80520001 (NS_ERROR_FILE_UNRECOGNIZED_PATH) [nsIFile.append]

FileUtils_getFile@resource://gre/modules/FileUtils.jsm:49:10
addPhoto@chrome://tbsync/content/modules/addressbook.js:407:30
setThunderbirdCardFromVCard@chrome://dav4tbsync/content/includes/tools.js:927:42
addContact@chrome://dav4tbsync/content/includes/tools.js:359:29
multiget@chrome://dav4tbsync/content/includes/sync.js:716:49
```

## Steps to reproduce
* Add nextcloud address book
* Synchronize
* Wait for error

I have sent a log of the offending contact entry via email. It seems that the DAV sync cannot handle a specific photo entry format which is well understood both by nextCloud and by Android's contact app.
I verified this by deleting the photo of the offending contact, then the sync for this contact went fine (but stopped at contact ~100 because of the same format being used  there).

From a layman's perspective:
In the best case, this photo format should be supported by tbsync; or at least, it should not lead to stopping the synchronization, instead, the photo should be ignored.

**Comment by jobisoft** [comment]
Thanks for the detailed report. Will look at it soon. Can you switch to the beta channel in the meantime, so you can test a fix as soon as I have one?
https://tbsync.jobisoft.de

**Comment by codeling** [comment]
@jobisoft I have already installed these beta xpi's from (https://tbsync.jobisoft.de/beta/TB68/) and could reproduce the issue exactly the same (that's what I tried to convey by putting an x between the [ ] above).

I also sent you an email with the debug.log in the meantime, hope this helps!

**Comment by codeling** [comment]
Ah sorry misread your message. Yes still have the beta versions on a secondary profile so I should be able to easily test a fix!

**Comment by jobisoft** [comment]
The reason is (probably) the type parameter of that photo. I do not comply with [RFC4288](https://tools.ietf.org/html/rfc4288) and the allowed (and even suggested) image suffix is causing this. And of course bad error handling. 

Workin on a fix.

**Comment by jobisoft** [comment]
I released version 1.9.1 of the DAV provider via the beta release channel. Could you give it a spin?

Just force-update your addons vie the gear menu in the Thunderbird Add-On Manger.

Fix is this: https://github.com/jobisoft/DAV-4-TbSync/commit/4667f5a0bbaeccd9a59ea3c8bfb80fcd86ca888a

**Comment by codeling** [comment]
I have done the update, DAV for TbSync is now at version 1.9.1 from today. But now I cannot do the test, as TbSync tells me that the DAV provider isn't installed; I already tried removing the existing account, and creating a new one (couldn't, because it again told me DAV provider isn't installed), and restarting thunderbird...

**Comment by jobisoft** [comment]
You need to go full beta (as described on the beta page): You need to remove all stable modules and install beta modules only.

**Comment by codeling** [comment]
Actually no other modules were installed, this was a newly created profile just with the beta modules. And after the update, above issue with missing provider occured. But still probably something I messed up; now with a completely new module with just those new .xpi files installed, it works again - but the synchronization still fails with a Javascript error - creating debug.log now

**Comment by jobisoft** [comment]
Stupid me.

Please update again, you might need to restart TB after it, because 1.9.1 is broken. Which also caused your observations.

**Comment by codeling** [comment]
Yes with 1.9.2 both errors (the issue with DAV not being available, and the original JavaScript error on sync) are gone!
Thanks for the extremely quick response!

**Comment by jobisoft** [comment]
Thanks, will be released as stable soon.
