### ISSUE TITLE
Connecxtion rejected error to SoGO 3 server

### ISSUE THREAD

**Issue by rainer042** [jobisoft/DAV-4-TbSync#75]
## Your environment

TbSync version: 1.5
DAV-4-TbSync version: 0.11
Thunderbird version: 60.3.0 on linux

[x ] Yes, I have installed the latest available (beta) version from 
 - https://github.com/jobisoft/TbSync/releases 
 - https://github.com/jobisoft/DAV-4-TbSync/releases 
and my issue is not yet fixed, I can still reproduce it.
[x] Afterwards I reinstalled the default versions of the addons

## Expected behavior
Sync of calendars from and to a SoGo 3 Server, that used to work a month ago

## Actual behavior
The addon reports an error that the connection to the SoSO-Server was rejected. On the server I see a 403 error for the URL requested. The complete error is:
-----
URL:
https://sogoserver/SOGo/dav/sharedcal/calendar-proxy-write/ (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:" xmlns:card="urn:ietf:params:xml:ns:carddav"><d:prop><card:addressbook-home-set /><d:group-membership /></d:prop></d:propfind>

Response:
<?xml version="1.0" encoding="ISO-8859-1"?>
<html xmlns="http://www.w3.org/1999/xhtml">
<body>
<h3>An error occurred during object publishing</h3>
<p>tried to access private object (0x0x561388091ad0, SoClass=SOGoCalendarProxy)</p>
</body>
</html>
-----

**Comment by jobisoft** [comment]
The "issue" is, that your server reports a principal URL of the type` calendar-proxy-read` or `calendar-proxy-write` after I asked him for group-membership (shared resources), but when I actually want to read those resources, i get an 403. 

If you have time, you could ask at SOGo, why that happens. SOGo is the only one with that behaviour. That feature (finding shared resources) had been introduced in the latest update. I may of course be doing something wrong.

Here is the full log of another user with the same issue:

```
** Sun Feb 10 2019 15:41:22 GMT+0100 (CET) **
[URL Request #1] : https://***/SOGo/dav/user1

** Sun Feb 10 2019 15:41:23 GMT+0100 (CET) **
[REQUEST] : PROPFIND
<?xml version="1.0"?>
<d:propfind xmlns:d="DAV:" xmlns:card="urn:ietf:params:xml:ns:carddav">
  <d:prop>
    <card:addressbook-home-set/>
    <d:group-membership/>
  </d:prop>
</d:propfind>

** Sun Feb 10 2019 15:41:23 GMT+0100 (CET) **
[RESPONSE] : 207
<?xml version="1.0" encoding="utf-8"?>
<D:multistatus xmlns:a="urn:ietf:params:xml:ns:carddav" xmlns:D="DAV:">
  <D:response>
    <D:href>/SOGo/dav/user1</D:href>
    <D:propstat>
      <D:status>HTTP/1.1 200 OK</D:status>
      <D:prop>
        <a:addressbook-home-set>
          <D:href xmlns:D="DAV:">/SOGo/dav/user1/Contacts/</D:href>
        </a:addressbook-home-set>
        <D:group-membership>
          <D:href xmlns:D="DAV:">/SOGo/dav/user2/calendar-proxy-write/</D:href>
        </D:group-membership>
      </D:prop>
    </D:propstat>
  </D:response>
</D:multistatus>

** Sun Feb 10 2019 15:41:23 GMT+0100 (CET) **
[URL Request #1] : https://***/SOGo/dav/user2/calendar-proxy-write/

** Sun Feb 10 2019 15:41:23 GMT+0100 (CET) **
[REQUEST] : PROPFIND
<?xml version="1.0"?>
<d:propfind xmlns:d="DAV:" xmlns:card="urn:ietf:params:xml:ns:carddav">
  <d:prop>
    <card:addressbook-home-set/>
    <d:group-membership/>
  </d:prop>
</d:propfind>

** Sun Feb 10 2019 15:41:23 GMT+0100 (CET) **
[RESPONSE] : 403
<?xml version="1.0" encoding="ISO-8859-1"?>
<html xmlns="http://www.w3.org/1999/xhtml">
<body><h3>An error occurred during object publishing</h3><p>tried to access private object (0x0x55bfc2b12b90, SoClass=SOGoCalendarProxy)</p></body>
</html>
```

**Comment by rainer042** [comment]
Thanks for your explanation. Well after all I have not much time. We told our users that they can use TBsync and Provider for caldav/carddav to sync with our sogo, which worked until recently. I guess a request to Sogo for this issue would not result in a solution in the near future because this would end up in me beeing a proxy between you and the sogo people, sitting between the chairs. Does not sound to be a good idea to me.
I understand that you just want to implement a new feature but this code broke the functionality of the addon at least for us whereas the older version just did what we needed.

The new group-membership feature allows to what I understand subscribing to "shared " resources, however I know exactly that using an older version of the addons I was already able to see and subscribe eg to shared calendars from other users. This worked just fine. This is something I do not understand?

Is there a repository where I could download the previous, still working versions?

**Comment by jobisoft** [comment]
I do not recommend to downgrade. I will release a fixed version today or tomorrow.

**Comment by rainer042** [comment]
This sounds great. Thanks a lot.
Rainer

**Comment by jobisoft** [comment]
I released a new beta, which should fix the issue. But I could not test it, because my SOGo TestServer is not throwing that 403. I have send a message to the sogo user list and hope to get an answer, what is causing this. For the moment I just skip any URL I get, which throws a 403.

To install the beta, follow the instructions here:
https://tbsync.jobisoft.de

I will release this as stable, as soon as I have positive feedback. If you find the time, please play around with the new support for more then 2 email addresses in the address book:

![image](https://user-images.githubusercontent.com/5830621/52677181-30c8a380-2f2d-11e9-91ea-c536b21a140b.png)

**@rainer042 If you are responsible for a larger user base, you could stay on the beta release channel, so you can see what changes are being made and we can catch such errors in the beta phase.**

**Comment by rainer042** [comment]
Hi, and thanks for the new (beta) version. I installed tbsync version 1.5.3 and  Provider für CalDAV 0.12.7 from the beta channel. Next I restarted thunderbird and deleted the sogo account and recreated it. However the error is still the same:

URL:
https://sogoserver/SOGo/dav/asharedcalendar/calendar-proxy-write/ (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/"><d:prop><cal:calendar-home-set /><cs:calendar-proxy-write-for /><cs:calendar-proxy-read-for /><d:group-membership /></d:prop></d:propfind>

Response:
<?xml version="1.0" encoding="ISO-8859-1"?>
<html xmlns="http://www.w3.org/1999/xhtml">
<body>
<h3>An error occurred during object publishing</h3>
<p>tried to access private object (0x0x561386889e70, SoClass=SOGoCalendarProxy)</p>
</body>
</html>

Your idea to stay the beta version to see potential problems in advance is a good one. Is there a mailinglist where new beta versions are announced?

**Comment by jobisoft** [comment]
Can you provide a test account, where I can reproduce that? You probably have to share something with me, credentials via email.

About the beta release channel: It will update automatically once per day.

**Comment by jobisoft** [comment]
I may have found another reason.

Please update your beta and try again:
![](https://raw.githubusercontent.com/jobisoft/TbSync/master/screenshots/update-addon.PNG)

**Comment by rainer042** [comment]
I just tested itagain. Success, now I can sync calendars and adresses  again.
Great!

Thanks a lot for you great help in finding and resolving this problem.

**Comment by jobisoft** [comment]
Nice.

For the future, I think I will no longer switch beta users back to stable, once a new stable is out (which I did last time), because I do need the Feedback from beta users.

I will add a notification, that a new stable is out, and the user may switch manually.

If you could stay on beta, that would help me a lot.

I will let this sit for another day or two, before releasing as new stable. The new address book stuff needs some feedback...

**Comment by rainer042** [comment]
I'll stay on the beta channel, so if I should experience any strange effects after an upgrade I will open a bug report to supply you with  feedback.  At the moment everything seems to work as expected again.
